Tugas Intro to Laravel/laravel-1/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\CastController;
use App\Http\Controllers\HomeController;

//Route::get('/', 'HomeController@index');

Route::get('/register', 'AuthController@form');

Route::post('/welcome', 'AuthController@hello');

Route::get('/', function() {
    return view('welcome');
});

Route::get('/master', function() {
    return view('AdminLTE.master');
});

Route::get('/items', function() {
    return view('items.index');
});

Route::get('/items/create', function() {
    return view('items.create');
});

// Route::get('/cast', 'CastController@index');
// Route::post('/cast', 'CastController@store');

// Route::get('/cast/create', 'CastController@create');

// Route::get('/cast/{id}', 'CastController@show');
// Route::get('/cast/{id}/edit', 'CastController@edit');

// Route::put('/cast/{id}', 'CastController@update');
// Route::delete('/cast/{id}', 'CastController@destroy');

Route::resource('cast', 'CastController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Tugas Intro to Laravel/laravel-1/app/Cast.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cast extends Model
{
    protected $table = "cast";
    protected $fillable = ["nama", "umur", "bio"];
    //protected $guarded = ["bio"];
}

Tugas Intro to Laravel/laravel-1/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

Tugas Intro to Laravel/laravel-1/app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AuthController extends Controller
{
    //
    public function form() {
        return view('form');
    } 
    public function hello(Request $request) {
        //dd($request->all());
        $first_name = $request["nama-depan"];
        $last_name = $request["nama-belakang"];
        return view('hello', ['first_name' => $first_name, 'last_name' => $last_name]);
    } 
}

Tugas Intro to Laravel/laravel-1/app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Cast;

class CastController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index']);
    }
    
    public function index() {
        // $casts = \DB::table('cast')->get();
        //dd($casts);
        $casts = Cast::all();
        return view('Cast.index', compact('casts'));
    }
    public function create() {
        return view('Cast.create');
    }
    public function store(Request $request) {
        //dd($request->all());   
        $request->validate([
            'nama' => 'required|unique:cast',
            'umur' => 'required',
            'bio' => 'required'
        ]);

        // $query = \DB::table('cast')->insert([
        //     "nama" => $request["nama"],
        //     "umur" => $request["umur"],
        //     "bio" => $request["bio"]
        // ]);

        // $cast = new Cast;
        // $cast->nama = $request["nama"];
        // $cast->umur = $request["umur"];
        // $cast->bio = $request["bio"];
        // $cast->save();

        $cast = Cast::create([
            "nama" => $request["nama"],
            "umur" => $request["umur"],
            "bio" => $request["bio"]
        ]);


        return redirect('/cast')->with('success', 'Cast Berhasil Ditambahkan!');
    }
    public function show($id) {
        // $cast = \DB::table('cast')->where('id',$id)->first();
        $cast = Cast::find($id);
        return view('Cast.show', compact('cast'));
    }
    public function edit($id) {
        // $cast = \DB::table('cast')->where('id',$id)->first();
        $cast = Cast::find($id);
        return view('Cast.edit', compact('cast'));
    }

    public function update($id, Request $request){
        $request->validate([
            'nama' => 'required|unique:cast',
            'umur' => 'required',
            'bio' => 'required'
        ]);
        // $cast = \DB::table('cast')
        //             ->where('id',$id)
        //             ->update([
        //                 'nama' => $request['nama'],
        //                 'umur' => $request['umur'],
        //                 'bio' => $request['bio']
        //             ]);
        $cast = Cast::where('id', $id)->update([
                        'nama' => $request['nama'],
                        'umur' => $request['umur'],
                        'bio' => $request['bio'] 
        ]);
            
        return redirect('/cast')->with('success', 'Berhasil Update Data!');
    }
    public function destroy($id) {
        // $cast = \DB::table('cast')->where('id',$id)->delete();
        $cast = Cast::destroy($id);
        return redirect('/cast')->with('success', 'Data berhasil di-delete!');
    }
}

Tugas Intro to Laravel/laravel-1/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

Tugas Intro to Laravel/laravel-1/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

Tugas Intro to Laravel/laravel-1/resources/views/AdminLTE/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Blank Page</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('/AdminLTE/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('/AdminLTE/dist/css/adminlte.min.css')}}">
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  @include('AdminLTE.partials.navbar')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('AdminLTE.partials.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @yield('content')
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.1.0
    </div>
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{ asset('AdminLTE/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('AdminLTE/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('AdminLTE/dist/js/demo.js')}}"></script>

@stack('scripts')

</body>
</html>

Tugas Intro to Laravel/laravel-1/resources/views/AdminLTE/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="../../index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('AdminLTE/dist/img/user8-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

Tugas Intro to Laravel/laravel-1/resources/views/Cast/create.blade.php
@extends('AdminLTE.master')

@section('content')
<div class="mt-3 ml-3">
<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Daftar Cast Baru</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="{{ route('cast.index')}}" method="POST">
      @csrf
      <div class="card-body">
        <div class="form-group">
          <label for="nama-cast">Nama</label>
          <input type="text" class="form-control" id="nama" name="nama" value="{{ old('nama', '')}}" placeholder="Nama">
          @error('nama')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="umur">Umur</label>
          <input type="text" class="form-control" id="umur" name="umur" value="{{ old('umur', '')}}" placeholder="Umur">
          @error('umur')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="bio">Bio</label>
          <input type="text" class="form-control" id="bio" name="bio" value="{{ old('bio', '')}}" placeholder="Bio">
          @error('bio')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>

      </div>
      <!-- /.card-body -->

      <div class="card-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
</div>
@endsection

Tugas Intro to Laravel/laravel-1/resources/views/Cast/edit.blade.php
@extends('AdminLTE.master')

@section('content')
<div class="mt-3 ml-3">
<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Edit Cast</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="{{ route('cast.update', ['cast' => $cast->id])}}" method="POST">
      @csrf
      @method('PUT')
      <div class="card-body">
        <div class="form-group">
          <label for="nama-cast">Nama</label>
          <input type="text" class="form-control" id="nama" name="nama" value="{{ old('nama', $cast->nama)}}" placeholder="Nama">
          @error('nama')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="umur">Umur</label>
          <input type="text" class="form-control" id="umur" name="umur" value="{{ old('umur', $cast->umur)}}" placeholder="Umur">
          @error('umur')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="bio">Bio</label>
          <input type="text" class="form-control" id="bio" name="bio" value="{{ old('bio', $cast->bio)}}" placeholder="Bio">
          @error('bio')
          <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>

      </div>
      <!-- /.card-body -->

      <div class="card-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
</div>
@endsection

Tugas Intro to Laravel/laravel-1/resources/views/Cast/index.blade.php
@extends('AdminLTE.master')

@section('content')
<div class="mt-3 ml-3">
    <div class="card">
        <div class="card-header">
          <h3 class="card-title">Daftar Cast</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          @if(session('success'))
            <div class="alert alert-success">
                {{ session('success')}}
            </div>
          @endif
          <a class="btn btn-primary mb-3" href="{{ route('cast.create')}}">Tambah Cast baru</a>
          <table class="table table-bordered">
            <thead>
              <tr>
                <th style="width: 10px">#</th>
                <th>Nama</th>
                <th>Umur</th>
                <th>Bio</th>
                <th style="width: 40px">Label</th>
              </tr>
            </thead>
            <tbody>
              @forelse ($casts as $key => $cast)
                  <tr>
                      <td> {{ $key + 1 }} </td>
                      <td> {{ $cast -> nama }} </td>
                      <td> {{ $cast -> umur }} </td>
                      <td> {{ $cast -> bio }} </td>
                      <td style="display: flex">  
                        <a href="{{ route('cast.show', ['cast' => $cast->id])}}" class="btn btn-info btn-sm">Detail</a>
                        <a href="{{ route('cast.edit', ['cast' => $cast->id])}}" class="btn btn-default btn-sm">Rubah</a>
                        <form action="{{ route('cast.destroy', ['cast' => $cast->id])}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <input type="submit" value="delete" class="btn btn-danger btn-sm">
                        </form>
                      </td>
                  </tr>
              @empty 
                  <tr>
                      <td colspan="5" align="center"> Tidak ada Data </td>
                  </tr>
              @endforelse
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
</div>
@endsection

Tugas Intro to Laravel/laravel-1/resources/views/Cast/show.blade.php
@extends('AdminLTE.master')

@section('content')
<div class="mt-3 ml-3">
    <h4>{{$cast->nama}}</h4>
    <h4>{{$cast->umur}}</h4>
    <h4>{{$cast->bio}}</h4>
</div>
@endsection

Tugas Intro to Laravel/laravel-1/resources/views/Items/create.blade.php
@extends('AdminLTE.master')

@section('content')
    <h2>Ini halaman create</h2>
@endsection

@push('scripts')
<script>
    var wrappers = document.getElementByClassName("wrappers");
    var items = ["ini", "contoh"];

    console.log("ini items: ", items)
</script>
    
@endpush

Tugas Intro to Laravel/laravel-1/resources/views/Items/index.blade.php
@extends('AdminLTE.master')

@section('content')
    <h1> Halo ini halaman index items </h1>    
@endsection

Tugas Intro to Laravel/laravel-1/resources/views/form.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="widh=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>
    <h1>Buat Account Baru!</h1>
    <h2>Sign Up Form</h2>
    <form action="/welcome" method="POST">
        @csrf
        <label> First Name: </label> <br><br>
        <input type="text" name="nama-depan"> <br><br>
        <label> Last Name: </label> <br><br>
        <input type="text" name="nama-belakang"> <br><br>
        <label> Gender: </label> <br><br>
        <input type="radio" name="male"> Male <br>
        <input type="radio" name="female"> Female <br>
        <input type="radio" name="other"> Other <br> <br>
        <label> Nationality: </label> <br><br>
        <select name="kebangsaan">
            <option value="1">Indonesian</option> <br>
            <option value="2">Singaporean</option> <br>
            <option value="3">Malaysian</option> <br>
            <option value="4">Australian</option> <br>
        </select> <br> <br>
        <label> Language Spoken: </label> <br> <br>
        <input type="checkbox"> Bahasa Indonesia <br>
        <input type="checkbox"> English <br>
        <input type="checkbox"> Other <br> <br>
        <label> Bio: </label> <br><br>
        <textarea name="bio" cols="30" rows="10"></textarea> <br> <br>
        <input type="submit" value="Sign Up">
    </form>
</body>
</html>

Tugas Intro to Laravel/laravel-1/resources/views/hello.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="widh=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>
    <h1>SELAMAT DATANG <?php echo "$first_name "; echo $last_name; ?> !</h1>
    <h2>Terima kasih telah bergabung di Sanberbook. Social media kita bersama!</h2>
</body>
</html>

Tugas Intro to Laravel/laravel-1/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Tugas Intro to Laravel/laravel-1/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>